In [60]:
import pandas as pd
import numpy as np
from datetime import timedelta
import matplotlib.pyplot as plt
import requests
import seaborn as sns
import json
import os
import datetime as dt
import re


from geopy import distance
from pandas.api.types import CategoricalDtype

In [61]:
df_2015 = pd.read_csv("recorridos-realizados-2015.csv")

In [62]:
df_2016 = pd.read_csv("recorridos-realizados-2016.csv")

In [63]:
df_2017 = pd.read_csv("recorridos-realizados-2017.csv")

In [64]:
df_2018 = pd.read_csv("recorridos-realizados-2018.csv")

In [65]:
df_2019 = pd.read_csv("recorridos-realizados-2019.csv")

#### Trabajamos el 2015

In [66]:
df_2015

,periodo,genero_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,long_estacion_origen,lat_estacion_origen,domicilio_estacion_origen,duracion_recorrido,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,long_estacion_destino,lat_estacion_destino,domicilio_estacion_destino
0,2015,M,2015-05-01 00:00:18,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla,0 days 00:26:24.000000000,2015-05-01 00:26:42,29,Parque Centenario,-58.434577,-34.608459,Patricias Argentinas y Carlos Finlay
1,2015,F,2015-05-01 00:02:06,17,Plaza Almagro,-58.418832,-34.606399,Plaza Almagro,0 days 00:57:53.000000000,2015-05-01 00:59:59,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla
2,2015,M,2015-05-01 00:02:53,17,Plaza Almagro,-58.418832,-34.606399,Plaza Almagro,0 days 01:03:08.000000000,2015-05-01 01:06:01,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla
3,2015,M,2015-05-01 00:08:01,29,Parque Centenario,-58.434577,-34.608459,Patricias Argentinas y Carlos Finlay,0 days 01:04:18.000000000,2015-05-01 01:12:19,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla
4,2015,M,2015-05-01 00:08:57,29,Parque Centenario,-58.434577,-34.608459,Patricias Argentinas y Carlos Finlay,0 days 01:09:41.000000000,2015-05-01 01:18:38,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
503247,2015,M,2015-12-31 19:58:54,2,Retiro,-58.374822,-34.592589,Av. Dr.Jose Ramos Mejia y Del Libertador Av,0 days 00:25:53.000000000,2015-12-31 20:24:47,3,Aduana,-58.368918,-34.611242,Av. Ing.Huergo y Av. Belgrano
503248,2015,M,2015-06-30 23:58:50,15,Cochabamba,NaN,NaN,NaN,0 days 00:25:04.000000000,2015-07-01 00:23:54,10,Puerto Madero - UCA,-58.365746,-34.615551,Moreau de Justo 1500
503249,2015,M,2015-08-31 23:57:45,12,Plaza Vicente López,-58.388949,-34.593177,Plaza Vicente López,0 days 00:53:54.000000000,2015-09-01 00:51:39,20,Distrito Audiovisual,-58.441789,-34.580036,Zapiola y Dorrego
503250,2015,M,2015-10-31 23:59:50,46,Chile,-58.374389,-34.616378,Perú 726,0 days 00:50:12.000000000,2015-11-01 00:50:02,14,Pacífico,-58.426320,-34.577787,Pacífico
503251,2015,M,2015-12-31 20:30:22,3,Aduana,-58.368918,-34.611242,Av. Ing.Huergo y Av. Belgrano,0 days 00:14:22.000000000,2015-12-31 20:44:44,11,Tribunales,-58.385022,-34.601313,Tribunales

In [67]:
df_2015.genero_usuario.unique()

array(['M', 'F'], dtype=object)

#### Trabajamos el 2016

In [68]:
df_2016.head(5)

,periodo,genero_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,long_estacion_origen,lat_estacion_origen,domicilio_estacion_origen,duracion_recorrido,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,long_estacion_destino,lat_estacion_destino,domicilio_estacion_destino
0,2016,M,2016-01-01 02:21:41,11,Tribunales,-58.385022,-34.601313,Tribunales,0 days 00:16:29.000000000,2016-01-01 02:48:05,5,Plaza Italia,-58.420997,-34.580127,Av. Santa Fe y Av. Sarmiento
1,2016,M,2016-01-01 08:38:19,28,Plaza Boedo,-58.412398,-34.622850,Carlos Calvo entre Virrey Liniers y Sánchez de...,0 days 00:55:26.000000000,2016-01-01 09:36:12,28,Plaza Boedo,-58.412398,-34.622850,Carlos Calvo entre Virrey Liniers y Sánchez de...
2,2016,M,2016-01-01 15:01:07,28,Plaza Boedo,-58.412398,-34.622850,Carlos Calvo entre Virrey Liniers y Sánchez de...,0 days 00:40:27.000000000,2016-01-01 16:04:15,30,Peña,-58.397378,-34.590394,Azcuénaga y Peña
3,2016,M,2016-01-01 15:14:36,5,Plaza Italia,-58.420997,-34.580127,Av. Santa Fe y Av. Sarmiento,0 days 00:45:44.000000000,2016-01-01 16:18:54,26,Juana Manso,-58.363604,-34.601001,Emma de la Barra y Juana Manso
4,2016,M,2016-01-01 15:48:51,30,Peña,-58.397378,-34.590394,Azcuénaga y Peña,0 days 00:44:09.000000000,2016-01-01 16:58:32,30,Peña,-58.397378,-34.590394,Azcuénaga y Peña

In [69]:
df_2016.genero_usuario.unique()

array(['M', 'F'], dtype=object)

#### Trabajamos 2017

In [70]:
df_2017.head(5)

,periodo,genero_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,long_estacion_origen,lat_estacion_origen,domicilio_estacion_origen,duracion_recorrido,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,long_estacion_destino,lat_estacion_destino,domicilio_estacion_destino
0,2017,M,2017-01-01 00:02:14,60.0,25 de Mayo,-58.371155,-34.601638,25 de Mayo y Lavalle,0 days 00:27:44.000000000,2017-01-01 00:28:38,4.0,Plaza Roma,-58.368950,-34.601721,Lavalle y Bouchard
1,2017,M,2017-01-01 00:02:59,79.0,Azucena Villaflor,-58.363969,-34.611721,Azucena Villaflor y Pierina Dealessi,0 days 01:57:21.000000000,2017-01-01 01:00:52,54.0,Acuña de Figueroa,-58.421705,-34.598222,Lavalle y Acuña de Figueroa
2,2017,M,2017-01-01 00:07:13,11.0,Tribunales,-58.385022,-34.601313,Tribunales,0 days 00:25:08.000000000,2017-01-01 01:10:21,84.0,Lavalle,-58.395472,-34.602290,Ayacucho 595 entre Tucumán y Lavalle
3,2017,M,2017-01-01 00:15:12,79.0,Azucena Villaflor,-58.363969,-34.611721,Azucena Villaflor y Pierina Dealessi,0 days 00:33:39.000000000,2017-01-01 01:19:30,74.0,Instituto Leloir,-58.434243,-34.604572,"Av. Patricias Argentinas 401, entre Juana de I..."
4,2017,M,2017-01-01 00:15:27,150.0,Vera Peñaloza,-58.363091,-34.618082,Rosario Vera Peñaloza y Olga Cossettini,0 days 00:20:23.000000000,2017-01-01 01:25:08,1.0,Facultad de Derecho,-58.392452,-34.583133,Av. Pres.Figueroa Alcorta y Juan A.Bibiloni

In [71]:
df_2017.genero_usuario.unique()

array(['M', 'F'], dtype=object)

#### Trabajamos 2018

In [72]:
df_2018.head(5)

,id_usuario,genero_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,long_estacion_origen,lat_estacion_origen,domicilio_estacion_origen,duracion_recorrido,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,long_estacion_destino,lat_estacion_destino,domicilio_estacion_destino
0,5453,M,2018-01-01 00:08:05,45.0,Uruguay,-58.386913,-34.601616,Tucumán y Uruguay,0 days 00:19:53.000000000,2018-01-01 00:27:58,183.0,Virrey Cevallos,-58.389692,-34.615638,México 1652 entre Virrey Cevallos y Solís
1,673,M,2018-01-01 00:18:05,189.0,Posadas,-58.385586,-34.588475,Posadas 1350 entre Montevideo y Rodríguez Peña,0 days 00:26:19.000000000,2018-01-01 00:44:24,110.0,Guardia Vieja,-58.415459,-34.601761,Guardia Vieja 3606 entre Billinghurst y Mario ...
2,179119,F,2018-01-01 00:20:14,50.0,Hospital Rivadavia,-58.401148,-34.583677,Lucena Pereyra 2516 entre Las Heras y Pagano,0 days 00:27:39.000000000,2018-01-01 00:47:53,31.0,Padilla,-58.439709,-34.603162,Padilla y Warnes Av
3,400147,M,2018-01-01 00:20:22,111.0,Macacha Güemes,-58.363000,-34.604969,Macacha Guemes y Juana Manso,0 days 00:48:51.000000000,2018-01-01 01:09:13,54.0,Acuña de Figueroa,-58.421705,-34.598222,Lavalle y Acuña de Figueroa
4,400156,F,2018-01-01 00:20:31,111.0,Macacha Güemes,-58.363000,-34.604969,Macacha Guemes y Juana Manso,0 days 00:49:27.000000000,2018-01-01 01:09:58,54.0,Acuña de Figueroa,-58.421705,-34.598222,Lavalle y Acuña de Figueroa

In [73]:
df_2018 = df_2018[df_2018.genero_usuario != "N"]

In [74]:
df_2018.genero_usuario.unique()

array(['M', 'F'], dtype=object)

In [75]:
df_2018["periodo"] = 2018

In [76]:
df_2018 = df_2018[["periodo",'id_usuario', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'domicilio_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'domicilio_estacion_destino']]

#### Trabajamos 2019

In [77]:
df_2019.head(5)

,id_usuario,edad_usuario,genero_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,direccion_estacion_origen,capacidad_estacion_origen,lat_estacion_origen,long_estacion_origen,duracion_recorrido,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,direccion_estacion_destino,capacidad_estacion_destino,lat_estacion_destino,long_estacion_destino,servicio
0,115783_0,36.0,FEMENINO,2019-01-01 00:01:16,168.0,Estados Unidos,Estados Unidos y Lima,NaN,-34.618620,-58.381283,0 days 00:07:02.000000000,2019-01-01 00:08:18,112.0,9 de Julio,9 de Julio y Moreno,NaN,-34.612389,-58.380766,antiguo
1,345364_0,40.0,MASCULINO,2019-01-01 00:04:32,47.0,Colegio Nacional Buenos Aires,Bolivar entre Adolfo Alsina y Moreno,NaN,-34.610782,-58.373557,0 days 00:05:33.000000000,2019-01-01 00:10:05,47.0,Colegio Nacional Buenos Aires,Bolivar entre Adolfo Alsina y Moreno,NaN,-34.610782,-58.373557,antiguo
2,570578_0,41.0,FEMENINO,2019-01-01 00:09:15,144.0,Pueyrredón,Boulogne Sur Mer y Tucuman,NaN,-34.601780,-58.405790,0 days 00:19:45.000000000,2019-01-01 00:29:00,44_0,Ecoparque,NaN,NaN,NaN,NaN,antiguo
3,588687_0,43.0,MASCULINO,2019-01-01 00:09:28,144.0,Pueyrredón,Boulogne Sur Mer y Tucuman,NaN,-34.601780,-58.405790,0 days 00:19:34.000000000,2019-01-01 00:29:02,44_0,Ecoparque,NaN,NaN,NaN,NaN,antiguo
4,127201_0,33.0,MASCULINO,2019-01-01 00:11:17,16.0,Legislatura,Perú y Diagonal Sur,NaN,-34.609959,-58.374717,0 days 00:21:32.000000000,2019-01-01 00:32:49,199.0,Estados Unidos y Boedo,Estados Unidos 3568 entre Boedo y Maza,NaN,-34.622439,-58.415882,antiguo

In [78]:
df_2019["genero_usuario"] = df_2019['genero_usuario'].astype(str).str[0]
df_2019["periodo"] = 2019

In [79]:
df_2019 = df_2019[df_2019.genero_usuario != "-"]
df_2019 = df_2019[df_2019.genero_usuario != 'N']
df_2019 = df_2019[df_2019.genero_usuario != "n"]
# df_2019 = df_2019[df_2019.genero_usuario != "nan"]

In [80]:
df_2019.genero_usuario.unique()

array(['F', 'M'], dtype=object)

In [81]:
df_2019 = df_2019[["periodo",'id_usuario', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'direccion_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'direccion_estacion_destino']]

#### Normalizamos las columnas

In [82]:
df_2015.columns

Index(['periodo', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'domicilio_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'domicilio_estacion_destino'],
      dtype='object')

In [83]:
df_2016.columns

Index(['periodo', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'domicilio_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'domicilio_estacion_destino'],
      dtype='object')

In [84]:
df_2017.columns

Index(['periodo', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'domicilio_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'domicilio_estacion_destino'],
      dtype='object')

In [85]:
df_2018.columns

Index(['periodo', 'id_usuario', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'domicilio_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'domicilio_estacion_destino'],
      dtype='object')

In [86]:
df_2019.columns

Index(['periodo', 'id_usuario', 'genero_usuario', 'fecha_origen_recorrido',
       'id_estacion_origen', 'nombre_estacion_origen', 'long_estacion_origen',
       'lat_estacion_origen', 'direccion_estacion_origen',
       'duracion_recorrido', 'fecha_destino_recorrido', 'id_estacion_destino',
       'nombre_estacion_destino', 'long_estacion_destino',
       'lat_estacion_destino', 'direccion_estacion_destino'],
      dtype='object')

#### Modificamos las columnas de 2019

In [87]:
df_2019 = df_2019.rename(columns={"direccion_estacion_origen": "domicilio_estacion_origen", "direccion_estacion_destino": "domicilio_estacion_destino"})

In [88]:
df_total_genero = pd.concat([df_2015,df_2016,df_2017,df_2018,df_2019])

In [89]:
df_total_genero

,periodo,genero_usuario,fecha_origen_recorrido,id_estacion_origen,nombre_estacion_origen,long_estacion_origen,lat_estacion_origen,domicilio_estacion_origen,duracion_recorrido,fecha_destino_recorrido,id_estacion_destino,nombre_estacion_destino,long_estacion_destino,lat_estacion_destino,domicilio_estacion_destino,id_usuario
0,2015,M,2015-05-01 00:00:18,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla,0 days 00:26:24.000000000,2015-05-01 00:26:42,29,Parque Centenario,-58.434577,-34.608459,Patricias Argentinas y Carlos Finlay,NaN
1,2015,F,2015-05-01 00:02:06,17,Plaza Almagro,-58.418832,-34.606399,Plaza Almagro,0 days 00:57:53.000000000,2015-05-01 00:59:59,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla,NaN
2,2015,M,2015-05-01 00:02:53,17,Plaza Almagro,-58.418832,-34.606399,Plaza Almagro,0 days 01:03:08.000000000,2015-05-01 01:06:01,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla,NaN
3,2015,M,2015-05-01 00:08:01,29,Parque Centenario,-58.434577,-34.608459,Patricias Argentinas y Carlos Finlay,0 days 01:04:18.000000000,2015-05-01 01:12:19,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla,NaN
4,2015,M,2015-05-01 00:08:57,29,Parque Centenario,-58.434577,-34.608459,Patricias Argentinas y Carlos Finlay,0 days 01:09:41.000000000,2015-05-01 01:18:38,25,Plaza Güemes,-58.416065,-34.589521,Salguero Jerónimo y Mansilla,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204102,2019,M,2019-02-22 08:00:13,174.0,Ministerio de Educación,-58.391549,-34.597261,Marcelo T De Alvear 1698 y Rodríguez Peña,0 days 00:07:01.000000000,2019-02-22 08:07:14,84.0,Lavalle,-58.395472,-34.602290,Ayacucho 595 entre Tucumán y Lavalle,693648_0
204103,2019,M,2019-02-22 08:00:16,169.0,Facultad de Psicología,-58.411925,-34.612020,Hipólito Yrigoyen y 24 de Noviembre,0 days 00:22:54.000000000,2019-02-22 08:23:10,102.0,Roseti,-58.445987,-34.586440,Roseti 50 y Av Dorrego,442313_0
204104,2019,M,2019-02-22 08:01:38,174.0,Ministerio de Educación,-58.391549,-34.597261,Marcelo T De Alvear 1698 y Rodríguez Peña,0 days 00:34:36.000000000,2019-02-22 08:36:14,146.0,Hospital Francés,-58.407788,-34.622194,Hospital Francés: Carlos Calvo y La Rioja,654559_0
204105,2019,F,2019-02-22 08:01:41,149.0,Lima,-58.381435,-34.615364,Lima y México,0 days 00:16:35.000000000,2019-02-22 08:18:16,33.0,Facultad de Medicina,-58.398717,-34.597127,Uriburu y Marcelo T. de Alvear,665868_0
204106,2019,F,2019-02-22 08:04:40,200.0,Austria y French,-58.404361,-34.588191,Austria 2080 entre French y Juncal,0 days 00:07:53.000000000,2019-02-22 08:12:33,64.0,Riobamba,-58.394440,-34.594149,Riobamba y Juncal,392691_0

#### Vemos la cantidad de nulos

In [90]:
def missing_values_table(df_total):
        mis_val = df_total_genero.isnull().sum()
        mis_val_percent = 100 * df_total.isnull().sum() / len(df_total)
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        print ("El DataFrame seleccionado tiene " + str(df_total.shape[1]) + " columnas.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columnas que tienen datos faltantes.")
        return mis_val_table_ren_columns

In [91]:
missing_values_table(df_total_genero)

El DataFrame seleccionado tiene 16 columnas.
There are 11 columnas que tienen datos faltantes.

                            Missing Values  % of Total Values
id_usuario                         2148217               43.2
fecha_destino_recorrido             682315               13.7
duracion_recorrido                   43854                0.9
long_estacion_destino                39742                0.8
lat_estacion_destino                 39742                0.8
domicilio_estacion_destino           39742                0.8
long_estacion_origen                 38954                0.8
lat_estacion_origen                  38954                0.8
domicilio_estacion_origen            38954                0.8
id_estacion_destino                  33982                0.7
id_estacion_origen                   33643                0.7

#### Dropeamos los nulos

In [92]:
df_total_genero = df_total_genero.dropna()
missing_values_table(df_total_genero)

El DataFrame seleccionado tiene 16 columnas.
There are 0 columnas que tienen datos faltantes.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

### Retocamos

In [93]:
df_total_genero["fecha_origen_recorrido"] = pd.to_datetime(df_total_genero['fecha_origen_recorrido'])
df_total_genero["fecha_destino_recorrido"] = pd.to_datetime(df_total_genero['fecha_destino_recorrido'])

In [94]:
df_total_genero[["id_estacion_origen", "id_estacion_destino"]] = df_total_genero[["id_estacion_origen", "id_estacion_destino"]].astype(float).round()

In [95]:
df_total_genero[["id_estacion_origen", "id_estacion_destino"]] = df_total_genero[["id_estacion_origen", "id_estacion_destino"]].astype(int)

In [96]:
df_total_genero[["id_estacion_origen", "id_estacion_destino"]].dtypes

id_estacion_origen     int32
id_estacion_destino    int32
dtype: object

In [97]:
# df_total_genero[["id_estacion_origen","id_estacion_destino"]]   = df_total_genero[["id_estacion_origen","id_estacion_destino"]].astype(int)

In [98]:
# Se crea la categoría "día" de la semana iterando sobre los siete días (4/3/2019 es lunes)
days = [(dt.datetime(2019, 3, 4) + dt.timedelta(days=x)).strftime('%a') for x in range(0, 7)]
day_type = CategoricalDtype(categories=days, ordered=True)

# Se crea la categoría "mes" iterando sobre los meses
months = [dt.datetime(2019, x, 1).strftime('%B') for x in range(1, 13)]
month_type = CategoricalDtype(categories=months, ordered=True)

In [99]:
# Se limpia en nombre de columna por caso de uso
#df.columns = [' '.join(x.replace('trip_', '').replace('_seconds', '').split('_')).title() for x in df.columns]

# df_total["fecha_origen_recorrido"] = pd.to_datetime(df_total["fecha_origen_recorrido"])

df_total_genero['Date'] = df_total_genero['fecha_origen_recorrido'].apply(lambda x: x.strftime('%Y-%m-%d'))
df_total_genero['Quarter'] = df_total_genero['fecha_origen_recorrido'].apply(lambda x: int((int(x.strftime('%m')) - 1) / 3) + 1)
df_total_genero['Month'] = df_total_genero['fecha_origen_recorrido'].apply(lambda x: x.strftime('%B')).astype(month_type)
df_total_genero['Day of Week'] = df_total_genero['fecha_origen_recorrido'].apply(lambda x: x.strftime('%a')).astype(day_type)
df_total_genero['Hour'] = df_total_genero['fecha_origen_recorrido'].apply(lambda x: x.strftime('%H'))

# Se crea la columna "Route ID" con el formato "[ID Estacion de Origen]-[ID Estacion de destino]" 
df_total_genero['Route Id'] = df_total_genero.apply(lambda x: '{0}-{1}'.format(int(x['id_estacion_origen']), int(x["id_estacion_destino"])), axis=1)

In [105]:
df_total_genero.to_csv("df_total_genero_normalizado.csv")